# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tao' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CHIPageControl/Jalapeno'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'FloatingPanel'
  pod 'razorpay-pod', '1.2.5'
  
  #  pod 'SwiftyMenu', '~> 1.0.0'
  # Pods for tao

end
